### PR TITLE
Added Badge for OpenAPM

### PR DESCRIPTION
**Pull request by L-1nk**
Hey @wu-sheng,

As suggested, here is the pull request for our openAPM-badge.
Would appreciate to see it online.

Regards,
Yaren

### CODE REVIEW

**Comment by wu-sheng** [comment]
How about we start with github readme?  This is a mirror of apache website, which we want to use new template.

**Comment by AlexanderWert** [comment]
Hi @wu-sheng ,

for the github readme, we would do it on the https://github.com/apache/incubator-skywalking repository, correct?

What is the process for submitting it to the website as well? Do we need to create the pull request directly on https://github.com/apache/incubator-skywalking-website ?

Thank you!

Regards,
Alex

**Comment by wu-sheng** [comment]
Yes. Website and main repo need vote to accept. So, begin with one, let's see.

**Comment by AlexanderWert** [comment]
OK, thank you @wu-sheng !
I've created a pull request on https://github.com/apache/incubator-skywalking for readme file!
So, you can close this pull request.

**Comment by wu-sheng** [comment]
Thanks. @AlexanderWert I will start a public vote. I think should be fine.

**Pull request closed without merging**
